"""Added resident table

Revision ID: 033373d6d3a3
Revises: a40d390bee18
Create Date: 2026-07-09 00:09:31.381021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033373d6d3a3'
down_revision: Union[str, Sequence[str], None] = 'a40d390bee18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('care_home_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['care_home_id'], ['care_homes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residents')
    # ### end Alembic commands ###
