"""add previous_role to users

Revision ID: 139c7c143afc
Revises: d9ab0cc42d8e
Create Date: 2026-07-14 11:31:29.864816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139c7c143afc'
down_revision: Union[str, Sequence[str], None] = 'd9ab0cc42d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('previous_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'previous_role')
    # ### end Alembic commands ###
