"""add otp rate limit fields to pending_users

Revision ID: 235f6401e3e6
Revises: bf6de77da376
Create Date: 2026-07-09 04:38:36.394896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235f6401e3e6'
down_revision: Union[str, Sequence[str], None] = 'bf6de77da376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_users', sa.Column('otp_request_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('pending_users', sa.Column('otp_window_start', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_users', 'otp_window_start')
    op.drop_column('pending_users', 'otp_request_count')
    # ### end Alembic commands ###
