"""add status column to handover_notes

Revision ID: 5d331b588b1d
Revises: e302ffae1ace
Create Date: 2026-07-11 02:33:02.790697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d331b588b1d'
down_revision: Union[str, Sequence[str], None] = 'e302ffae1ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handover_notes', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    op.add_column('handover_notes', sa.Column('error_message', sa.String(), nullable=True))
    op.alter_column('handover_notes', 'raw_transcript',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('handover_notes', 'summary_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('handover_notes', 'urgency_flag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_handover_notes_resident_id'), 'handover_notes', ['resident_id'], unique=False)
    op.create_index(op.f('ix_handover_notes_shift_id'), 'handover_notes', ['shift_id'], unique=False)
    op.create_index(op.f('ix_handover_notes_urgency_flag'), 'handover_notes', ['urgency_flag'], unique=False)
    op.drop_constraint(op.f('handover_notes_shift_id_fkey'), 'handover_notes', type_='foreignkey')
    op.create_foreign_key(None, 'handover_notes', 'shifts', ['shift_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_residents_care_home_id'), 'residents', ['care_home_id'], unique=False)
    op.drop_constraint(op.f('residents_care_home_id_fkey'), 'residents', type_='foreignkey')
    op.create_foreign_key(None, 'residents', 'care_homes', ['care_home_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_shifts_worker_id'), 'shifts', ['worker_id'], unique=False)
    op.create_index(op.f('ix_users_care_home_id'), 'users', ['care_home_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_care_home_id'), table_name='users')
    op.drop_index(op.f('ix_shifts_worker_id'), table_name='shifts')
    op.drop_constraint(None, 'residents', type_='foreignkey')
    op.create_foreign_key(op.f('residents_care_home_id_fkey'), 'residents', 'care_homes', ['care_home_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_residents_care_home_id'), table_name='residents')
    op.drop_constraint(None, 'handover_notes', type_='foreignkey')
    op.create_foreign_key(op.f('handover_notes_shift_id_fkey'), 'handover_notes', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_handover_notes_urgency_flag'), table_name='handover_notes')
    op.drop_index(op.f('ix_handover_notes_shift_id'), table_name='handover_notes')
    op.drop_index(op.f('ix_handover_notes_resident_id'), table_name='handover_notes')
    op.alter_column('handover_notes', 'urgency_flag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('handover_notes', 'summary_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('handover_notes', 'raw_transcript',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('handover_notes', 'error_message')
    op.drop_column('handover_notes', 'status')
    # ### end Alembic commands ###
