"""add assignment system

Revision ID: 63519c84123e
Revises: 6a229def2048
Create Date: 2026-08-06 12:20:40.149390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63519c84123e'
down_revision: Union[str, Sequence[str], None] = '6a229def2048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resident_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('care_worker_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['care_worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id', 'care_worker_id', name='uq_resident_care_worker')
    )
    op.create_index(op.f('ix_resident_assignments_care_worker_id'), 'resident_assignments', ['care_worker_id'], unique=False)
    op.create_index(op.f('ix_resident_assignments_resident_id'), 'resident_assignments', ['resident_id'], unique=False)
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_column('users', 'manager_id')
    op.drop_index(op.f('ix_resident_assignments_resident_id'), table_name='resident_assignments')
    op.drop_index(op.f('ix_resident_assignments_care_worker_id'), table_name='resident_assignments')
    op.drop_table('resident_assignments')
    # ### end Alembic commands ###
