"""add manager care home field

Revision ID: 6a229def2048
Revises: e9484ba26229
Create Date: 2026-08-06 11:36:48.757730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a229def2048'
down_revision: Union[str, Sequence[str], None] = 'e9484ba26229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('care_home', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'care_home')
    # ### end Alembic commands ###
