"""expand resident profile fields

Revision ID: 7eeb9d47ddc5
Revises: 8aaa3c4dc882
Create Date: 2026-08-06 11:13:50.110121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eeb9d47ddc5'
down_revision: Union[str, Sequence[str], None] = '8aaa3c4dc882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residents', sa.Column('preferred_name', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('residents', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('resident_code', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('residents', sa.Column('room_number', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('ward_unit', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('medical_conditions', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('residents', sa.Column('allergies', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('residents', sa.Column('current_medications', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('residents', sa.Column('disability', sa.Text(), nullable=True))
    op.add_column('residents', sa.Column('mobility_status', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('dietary_requirements', sa.Text(), nullable=True))
    op.add_column('residents', sa.Column('communication_requirements', sa.Text(), nullable=True))
    op.add_column('residents', sa.Column('sensory_loss', sa.Text(), nullable=True))
    op.add_column('residents', sa.Column('care_level', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('behaviour_notes', sa.Text(), nullable=True))
    op.add_column('residents', sa.Column('daily_care_notes', sa.Text(), nullable=True))
    op.add_column('residents', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('ethnicity', sa.String(), nullable=True))
    op.add_column('residents', sa.Column('preferred_language', sa.String(), nullable=True))
    op.create_index(op.f('ix_residents_resident_code'), 'residents', ['resident_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_residents_resident_code'), table_name='residents')
    op.drop_column('residents', 'preferred_language')
    op.drop_column('residents', 'ethnicity')
    op.drop_column('residents', 'religion')
    op.drop_column('residents', 'emergency_contact_phone')
    op.drop_column('residents', 'emergency_contact_relationship')
    op.drop_column('residents', 'emergency_contact_name')
    op.drop_column('residents', 'daily_care_notes')
    op.drop_column('residents', 'behaviour_notes')
    op.drop_column('residents', 'risk_level')
    op.drop_column('residents', 'care_level')
    op.drop_column('residents', 'sensory_loss')
    op.drop_column('residents', 'communication_requirements')
    op.drop_column('residents', 'dietary_requirements')
    op.drop_column('residents', 'mobility_status')
    op.drop_column('residents', 'disability')
    op.drop_column('residents', 'current_medications')
    op.drop_column('residents', 'allergies')
    op.drop_column('residents', 'medical_conditions')
    op.drop_column('residents', 'ward_unit')
    op.drop_column('residents', 'room_number')
    op.drop_column('residents', 'admission_date')
    op.drop_column('residents', 'resident_code')
    op.drop_column('residents', 'gender')
    op.drop_column('residents', 'date_of_birth')
    op.drop_column('residents', 'preferred_name')
    # ### end Alembic commands ###
