"""add resolved_follow_ups to handover_notes

Revision ID: 8aaa3c4dc882
Revises: 994aa4897d0d
Create Date: 2026-08-05 16:22:59.226910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aaa3c4dc882'
down_revision: Union[str, Sequence[str], None] = '994aa4897d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.add_column('handover_notes', sa.Column('resolved_follow_ups', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_index(op.f('ix_handover_notes_created_at'), table_name='handover_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_handover_notes_created_at'), 'handover_notes', ['created_at'], unique=False)
    op.drop_column('handover_notes', 'resolved_follow_ups')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
