"""Added care_homes table and added fk in user table

Revision ID: a40d390bee18
Revises: 8a155fd8f8b9
Create Date: 2026-07-09 00:08:05.961185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40d390bee18'
down_revision: Union[str, Sequence[str], None] = '8a155fd8f8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_homes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('care_home_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'care_homes', ['care_home_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'care_home_id')
    op.drop_table('care_homes')
    # ### end Alembic commands ###
