"""add_status_and_discharged_at_to_resident

Revision ID: a727fd17eaa5
Revises: 5d331b588b1d
Create Date: 2026-07-14 10:39:18.925171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a727fd17eaa5'
down_revision: Union[str, Sequence[str], None] = '5d331b588b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residents', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('residents', sa.Column('discharged_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residents', 'discharged_at')
    op.drop_column('residents', 'status')
    # ### end Alembic commands ###
