"""remove_care_homes_and_add_notifications

Revision ID: d9ab0cc42d8e
Revises: a727fd17eaa5
Create Date: 2026-07-14 11:07:03.005358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ab0cc42d8e'
down_revision: Union[str, Sequence[str], None] = 'a727fd17eaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('urgency_flag', sa.String(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('handover_note_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handover_note_id'], ['handover_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_handover_note_id'), 'notifications', ['handover_note_id'], unique=False)
    op.create_index(op.f('ix_notifications_resident_id'), 'notifications', ['resident_id'], unique=False)
    op.create_index(op.f('ix_notifications_urgency_flag'), 'notifications', ['urgency_flag'], unique=False)
    op.drop_constraint('pending_users_care_home_id_fkey', 'pending_users', type_='foreignkey')
    op.drop_column('pending_users', 'care_home_id')
    op.drop_index('ix_residents_care_home_id', table_name='residents')
    op.drop_constraint('residents_care_home_id_fkey', 'residents', type_='foreignkey')
    op.drop_column('residents', 'care_home_id')
    op.drop_index('ix_users_care_home_id', table_name='users')
    op.drop_constraint('users_care_home_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'care_home_id')
    op.drop_table('care_homes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('care_home_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_care_home_id_fkey'), 'users', 'care_homes', ['care_home_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_care_home_id'), 'users', ['care_home_id'], unique=False)
    op.add_column('residents', sa.Column('care_home_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('residents_care_home_id_fkey'), 'residents', 'care_homes', ['care_home_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_residents_care_home_id'), 'residents', ['care_home_id'], unique=False)
    op.add_column('pending_users', sa.Column('care_home_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pending_users_care_home_id_fkey'), 'pending_users', 'care_homes', ['care_home_id'], ['id'], ondelete='SET NULL')
    op.create_table('care_homes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('care_homes_pkey'))
    )
    op.drop_index(op.f('ix_notifications_urgency_flag'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_resident_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_handover_note_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
