"""add care worker employment fields

Revision ID: e9484ba26229
Revises: 7eeb9d47ddc5
Create Date: 2026-08-06 11:33:17.687644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9484ba26229'
down_revision: Union[str, Sequence[str], None] = '7eeb9d47ddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('home_address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('shift_pattern', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employment_status', sa.String(), server_default='active', nullable=False))
    op.add_column('users', sa.Column('join_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_relationship')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'join_date')
    op.drop_column('users', 'employment_status')
    op.drop_column('users', 'shift_pattern')
    op.drop_column('users', 'department')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'home_address')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
